name: release

on:
  push:
    tags: ['v*.*.*'] # only a valid semver tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install
        run: make install-build
      - name: Build
        run: make dist
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
